#!/usr/bin/env python3
"""
Wire docs/letter_writers.json into compare-purple-gold.html.

For each record, find the matching <h3><a href=URL>NAME</a></h3> in the
mentor / collaborator / peer cards and inject a <p class="field-of-interest">
right after the role line that follows the name.

Idempotent: re-running overwrites any prior field-of-interest line for the
same person. Safe to run after every letter_writers.json refresh.

Run:
    python3 scripts/wire_letter_writers.py
        wires into compare-purple-gold.html in place

    python3 scripts/wire_letter_writers.py --dry-run
        prints what would change, does not write
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "compare-purple-gold.html"
DATA = ROOT / "docs" / "letter_writers.json"

LOW_CONF_THRESHOLD = 0.6
MAX_TERMS_SHOWN = 4

# Sentinel comment used to bookend an injected field-of-interest paragraph.
# Lets re-runs strip the previous version cleanly.
SENTINEL_OPEN = "<!--field-of-interest:start-->"
SENTINEL_CLOSE = "<!--field-of-interest:end-->"

# Style block injected once at the top of the existing inline styles.
# Uses theme tokens already defined in compare-purple-gold.html.
STYLE_BLOCK = """
/* Letter-writer field-of-interest — generated by scripts/wire_letter_writers.py */
.field-of-interest {
    color: var(--accent-dark);
    font-size: 0.78rem;
    font-weight: 600;
    letter-spacing: 0.2px;
    margin-top: 6px;
    margin-bottom: 4px;
    line-height: 1.4;
}
.field-of-interest.low-conf {
    color: var(--text-muted);
    font-weight: 500;
    font-style: italic;
}
.field-of-interest .foi-label {
    color: var(--primary);
    text-transform: uppercase;
    font-size: 0.68rem;
    letter-spacing: 1px;
    margin-right: 4px;
}
"""

STYLE_SENTINEL = "/* field-of-interest-styles */"


def build_paragraph(record: dict) -> str:
    """Build the field-of-interest <p> for one record."""
    conf = float(record.get("confidence", 0.0))
    terms = [t for t in record.get("field_terms", []) if t]
    n_pubs = len(record.get("recent_pmids", []))
    if conf <= LOW_CONF_THRESHOLD:
        body = "verifying field-of-interest"
        if terms:
            body += f" (provisional: {', '.join(terms[:2])})"
        return (
            f'{SENTINEL_OPEN}<p class="field-of-interest low-conf" '
            f'data-name="{escape_attr(record["name"])}" data-conf="{conf}">'
            f'<span class="foi-label">Recent focus</span>{escape_text(body)}'
            f"</p>{SENTINEL_CLOSE}"
        )
    shown = ", ".join(terms[:MAX_TERMS_SHOWN])
    return (
        f'{SENTINEL_OPEN}<p class="field-of-interest" '
        f'data-name="{escape_attr(record["name"])}" data-conf="{conf}">'
        f'<span class="foi-label">Recent focus</span>{escape_text(shown)} '
        f'<span style="color:var(--text-muted); font-weight:500;">'
        f'· {n_pubs} recent pubs</span>'
        f"</p>{SENTINEL_CLOSE}"
    )


def escape_attr(s: str) -> str:
    return s.replace('"', "&quot;").replace("<", "&lt;").replace(">", "&gt;")


def escape_text(s: str) -> str:
    return s.replace("<", "&lt;").replace(">", "&gt;").replace("&", "&amp;")


def strip_existing_foi(html: str, name: str) -> str:
    """Remove any previously-injected field-of-interest <p> for this name."""
    pat = re.compile(
        re.escape(SENTINEL_OPEN)
        + r'<p\s+class="field-of-interest[^"]*"\s+data-name="'
        + re.escape(escape_attr(name))
        + r'"[^>]*>.*?</p>'
        + re.escape(SENTINEL_CLOSE),
        re.DOTALL,
    )
    return pat.sub("", html)


def inject_record(html: str, record: dict) -> tuple:
    """
    Find the <h3> containing <a ...>NAME</a> and inject our <p> after the
    immediately-following <p ...> (the role line).

    Returns (new_html, did_change).
    """
    name = record["name"]
    html_after_strip = strip_existing_foi(html, name)
    paragraph = build_paragraph(record)

    # Anchor: the <h3>...<a href=URL>NAME</a>...</h3> block followed by a <p>.
    # We match the name literally; collaborator/peer/mentor cards all use this shape.
    h3_pattern = re.compile(
        r'(<h3[^>]*>\s*<a[^>]*>\s*'
        + re.escape(name)
        + r'\s*</a>\s*</h3>\s*<p[^>]*>.*?</p>)',
        re.DOTALL,
    )

    def repl(m):
        return m.group(1) + "\n                    " + paragraph

    new_html, n = h3_pattern.subn(repl, html_after_strip, count=0)  # 0 = all occurrences
    return new_html, n > 0


def ensure_style_block(html: str) -> str:
    """Inject the CSS once, idempotently, in the first <style> block."""
    if STYLE_SENTINEL in html:
        return html
    style_open = re.search(r"<style[^>]*>", html)
    if not style_open:
        return html
    insert_at = style_open.end()
    payload = "\n" + STYLE_SENTINEL + STYLE_BLOCK
    return html[:insert_at] + payload + html[insert_at:]


def wire(html: str, data: dict) -> tuple:
    """Inject all records. Returns (new_html, n_injected, n_missing)."""
    html = ensure_style_block(html)
    n_injected = 0
    missing = []
    for record in data.get("records", []):
        new_html, did_change = inject_record(html, record)
        if did_change:
            html = new_html
            n_injected += 1
        else:
            missing.append(record["name"])
    return html, n_injected, missing


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--site", default=str(SITE))
    ap.add_argument("--data", default=str(DATA))
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    site_path = Path(args.site)
    data_path = Path(args.data)
    if not site_path.exists():
        print(f"site not found: {site_path}", file=sys.stderr)
        return 2
    if not data_path.exists():
        print(f"data not found: {data_path}", file=sys.stderr)
        return 2

    html = site_path.read_text(encoding="utf-8")
    data = json.loads(data_path.read_text(encoding="utf-8"))
    new_html, n_injected, missing = wire(html, data)
    print(f"Injected: {n_injected}")
    if missing:
        print(f"Could not match {len(missing)} (name not in site or layout changed):")
        for m in missing:
            print(f"  - {m}")
    if args.dry_run:
        print("(dry run — no write)")
        return 0
    if new_html == html:
        print("(no change)")
        return 0
    site_path.write_text(new_html, encoding="utf-8")
    print(f"Wrote {site_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
