#!/usr/bin/env python3
"""
Wire the live Archivist publications feed into compare-purple-gold.html.

Renders the complete, auto-fresh publication list (from the counter-signed
Archivist feed via publications_feed.py) into the #publications section, BELOW
the curated Q-tagged "Selected Papers" showcase — so the showcase design is
preserved and the section also carries a living, provenance-stamped full list.

Build-time render (the site has no runtime): re-run this whenever the feed
refreshes to keep the served HTML fresh. Idempotent — a sentinel-bounded block
is stripped and re-injected each run, so repeated runs are byte-stable.

Data Provenance (orchestra.md): the block always stamps `data_as_of` + the
count; if the feed is >14d stale it renders a loud banner; if the feed file is
missing it renders a fallback notice and leaves the curated showcase intact
(never a silent stale snapshot).

Run:
    python3 scripts/wire_publications.py            # wire in place
    python3 scripts/wire_publications.py --dry-run  # print, no write
"""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from publications_feed import load_feed, render_html, DEFAULT_FEED_PATH  # noqa: E402

SITE = ROOT / "compare-purple-gold.html"

SENTINEL_OPEN = "<!--publications-feed:start-->"
SENTINEL_CLOSE = "<!--publications-feed:end-->"
STYLE_SENTINEL = "/* publications-feed-styles */"
STYLE_SENTINEL_END = "/* publications-feed-styles:end */"

# Styles for the feed-rendered block. Tokens only (web-quality rule 1); mirrors
# the site's existing scale so the living list sits cleanly under the showcase.
STYLE_BLOCK = """
/* Publications feed — generated by scripts/wire_publications.py */
.pub-feed { margin-top: var(--space-10); border-top: 1px solid var(--accent); padding-top: var(--space-6); }
.pub-feed-meta {
    font-size: var(--font-size-sm); color: var(--text-muted); font-weight: 600;
    letter-spacing: 0.3px; margin-bottom: var(--space-4);
}
.pub-feed-meta a { color: var(--accent-dark); border-bottom: 1px dotted var(--accent); }
.pub-feed .freshness-banner {
    font-size: var(--font-size-sm); color: var(--primary); font-weight: 600;
    background: rgba(197,163,54,0.12); border-left: 3px solid var(--accent);
    padding: var(--space-2) var(--space-3); border-radius: var(--radius-sm);
    margin-bottom: var(--space-4);
}
.pub-feed .arc-heading {
    font-size: var(--font-size-lg); color: var(--primary); font-weight: 700;
    margin-top: var(--space-6); margin-bottom: var(--space-2);
}
.pub-feed .publication-list { list-style: none; padding: 0; margin: 0; }
.pub-feed .publication-list li {
    font-size: var(--font-size-base); line-height: 1.6; color: var(--text);
    padding: var(--space-2) 0; border-bottom: 1px solid rgba(0,0,0,0.06);
}
.pub-feed .publication-list a { color: var(--primary); font-weight: 600; }
.pub-feed .pub-badge {
    display: inline-block; font-size: var(--font-size-xs); text-transform: uppercase;
    letter-spacing: 0.5px; color: var(--primary); background: rgba(197,163,54,0.15);
    padding: 0 var(--space-2); border-radius: var(--radius-pill); margin-left: var(--space-1);
}
"""  # noqa: E501 — badge text is --primary (11.59:1 on the gold tint); --accent-dark
# was 4.43:1, UNDER WCAG-AA 4.5 for normal-size text (WEB-QUALITY gate, 2026-07-03).

PUBMED_URL = "https://pubmed.ncbi.nlm.nih.gov/?term=Roizen+JD"


def build_block(feed_path: Path) -> str:
    """Build the sentinel-bounded publications-feed block (fresh list or fallback)."""
    result = load_feed(feed_path)
    if result is None or result.error or not result.publications:
        # Fallback: feed missing/invalid — loud notice, curated showcase stays authoritative.
        reason = "temporarily unavailable" if result is None else "could not be parsed"
        inner = (
            '<div class="pub-feed">'
            f'<p class="freshness-banner">Live publications feed {reason} — '
            "showing the curated highlights above.</p>"
            "</div>"
        )
        return f"{SENTINEL_OPEN}{inner}{SENTINEL_CLOSE}"

    as_of = result.data_as_of.strftime("%Y-%m-%d") if result.data_as_of else "unknown date"
    n = len(result.publications)
    meta = (
        f'<p class="pub-feed-meta">Complete list — {n} publications, verified '
        f'{as_of} · <a href="{PUBMED_URL}">full record on PubMed</a></p>'
    )
    # render_html already prepends a staleness banner when >14 days stale.
    inner = f'<div class="pub-feed">{meta}\n{render_html(result)}</div>'
    return f"{SENTINEL_OPEN}{inner}{SENTINEL_CLOSE}"


def _find_real_style_open(html: str):
    """First <style> opening tag that is NOT inside an HTML comment.

    A naive `<style[^>]*>` match hits the '<style>' substring inside comments like
    "@font-face inlined in <style> below", burying the CSS in the comment where it
    never parses (bug caught 2026-07-03). We skip any match whose nearest preceding
    comment delimiter is an unclosed '<!--'.
    """
    import re
    for m in re.finditer(r"<style[^>]*>", html):
        prefix = html[: m.start()]
        if prefix.rfind("<!--") > prefix.rfind("-->"):
            continue  # inside a comment
        return m
    return None


def ensure_style_block(html: str) -> str:
    """(Re)inject the feed styles so the SCRIPT is the authoritative source.

    Strip any existing start..end block (AND its leading newline, so re-runs are
    byte-stable — the whitespace-accumulation class) and re-inject the current
    STYLE_BLOCK. This lets a style change here (e.g. the badge AA fix) propagate
    on the next wire, instead of being frozen at first-injection.
    """
    import re
    html = re.sub(
        r"\n?" + re.escape(STYLE_SENTINEL) + r".*?" + re.escape(STYLE_SENTINEL_END),
        "", html, flags=re.DOTALL,
    )
    m = _find_real_style_open(html)
    if not m:
        return html
    at = m.end()
    payload = "\n" + STYLE_SENTINEL + STYLE_BLOCK + STYLE_SENTINEL_END
    return html[:at] + payload + html[at:]


_INJECT_INDENT = "\n            "


def wire(html: str, feed_path: Path) -> str:
    import re
    html = ensure_style_block(html)
    # Strip any prior block AND the leading newline+indent inject() prepends, so
    # strip+inject is a true byte-stable round-trip (else the whitespace orphans
    # and accumulates one run per re-wire — the cron-compounding class, 2026-06-18).
    html = re.sub(
        r"(?:\n[ \t]*)?" + re.escape(SENTINEL_OPEN) + r".*?" + re.escape(SENTINEL_CLOSE),
        "", html, flags=re.DOTALL,
    )
    block = build_block(feed_path)
    # Inject before the closing </section> of #publications.
    m = re.search(r'(<section id="publications".*?)(</section>)', html, re.DOTALL)
    if not m:
        raise RuntimeError("could not find #publications section to wire into")
    insert_at = m.end(1)
    return html[:insert_at] + _INJECT_INDENT + block + html[insert_at:]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--site", default=str(SITE))
    ap.add_argument("--feed", default=str(DEFAULT_FEED_PATH))
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    site_path = Path(args.site)
    if not site_path.exists():
        print(f"site not found: {site_path}", file=sys.stderr)
        return 2
    html = site_path.read_text(encoding="utf-8")
    new_html = wire(html, Path(args.feed))
    if args.dry_run:
        import re
        block = re.search(
            re.escape(SENTINEL_OPEN) + r".*?" + re.escape(SENTINEL_CLOSE),
            new_html, re.DOTALL)
        print(block.group(0) if block else "(no block produced)")
        return 0
    if new_html == html:
        print("(no change)")
        return 0
    site_path.write_text(new_html, encoding="utf-8")
    print(f"Wired publications feed into {site_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
